DROP TABLE users;
DROP TABLE cities;

CREATE TABLE IF NOT EXISTS cities (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(10) PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  city_id INT NULL,
  FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE RESTRICT
);